### ISSUE TITLE
Multi-Column Blib-List

### ISSUE THREAD

**Issue by rdmueller** [anoff/devradar#42]
The list of blibs is too wide on a larger Screen. It would be great if it could be displayed in 3 to 4 columns.

**Comment by anoff** [comment]
I don't get what you mean 🙄. Are you talking about the radar or the list view?

**Comment by rdmueller** [comment]
the list view...

**Comment by anoff** [comment]
any more input on this? Otherwise I'll close it because I don't understand what you mean 😛

**Comment by rdmueller** [comment]
thanx for the reminder...
current view is like this:

![devradar1](https://user-images.githubusercontent.com/1856308/63294456-ae99ad00-c2ca-11e9-8b4a-1a93f8bec321.png)
all blibs are ordered as list, no matter how wide the screen is.

It would be great to have at least two or three columns like this:
![devradar2](https://user-images.githubusercontent.com/1856308/63294520-d0932f80-c2ca-11e9-9bc3-68a3a727c309.png)

This could give you a better overview.... and use the space more efficiently.

**Comment by anoff** [comment]
How would you split the columns and expect scrolling to work? Looks a bit like a Kanban board, how about adding one column per skill level? i.e. leftmost is level=0 and right is level=3?
Would probably require horizontal scrolling

**Comment by rdmueller** [comment]
I would display the skills as cards in a responsive layout. maybe three columns which switch to one oclumn when it gets too small

**Comment by anoff** [comment]
Anyone that wants to work on this; here are a few hints:

[This](https://github.com/anoff/devradar/blob/master/editor/src/components/List.vue#L30) is where the skills are rendered.
Currently using a [vuetify 1.5 grid layout](https://v15.vuetifyjs.com/en/framework/grid) that is specified with `xs12` meaning on the smallest breakpoint (xs) the column will have a grid with of 12 (out of 12) meaning full width.

The way to solve this issue is to probably keep `xs12` because small devices should only show a single column. However larger devices should show multiple columns, so adding additional elements that only show up for larger breakpoints would allow the transition from one to multiple columns.
Splitting up the content between these might be a bit tricky and require work on the Javascript code as well. Feel free to contact me if you are working on it and get stuck.

To develop locally; install nodeJS clone the repo bring up the development build running on **localhost:8080** with

```bash
cd editor
npm install
npm run serve
```
